### ISSUE TITLE
Fail installing dependencies to develop (pip install -e .[dev])

### ISSUE THREAD

**Issue by abispo** [ashleysommer/sanic-restplus#4]
Hi! I cannot install the dependencies in file `requirements/develop.pip`. When I run the `pip install -e .[dev]` command,  pip returns the following output:

> sanic-restplus 0.3.1.dev20180411 does not provide the extra 'dev'

Running with other options (test and doc) works perfectly.

**Comment by ashleysommer** [comment]
Thanks for the report.

I'll look into it.

**Comment by ashleysommer** [comment]
I believe this is resolved now and it can be closed.
