### ISSUE TITLE
Failed to install sanic-restplus using pip3

### ISSUE THREAD

**Issue by hoony9x** [ashleysommer/sanic-restplus#5]
I tried below command.

```sh
$ pip3 install sanic-restplus
```

and it makes below results.

```sh
Collecting sanic-restplus
  Could not find a version that satisfies the requirement sanic-restplus (from versions: )
No matching distribution found for sanic-restplus
```

How to solve this problem?

**Comment by ashleysommer** [comment]
sanic restplus is not available on pypi yet. So you cannot install it using pip.

There is section in the README that explains this.
>I intend to release Sanic-restplus on pypi when it is finished being ported from Flask to Sanic.
>
>However in its current state I believe it is not yet ready to be submitted to pypi.
>
>There are still references to modules from Flask and Werkzeug in the code, which I need to remove and provide workaround functionality. Also in its current state it will crash, a lot.
